apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: classical-planarian-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: classical-planarian-nodejs 
  name: classical-planarian-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: classical-planarian-nodejs 
