apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: classical-planarian-nodejs-gitops
  description: This is GitOps manifest for classical-planarian-nodejs   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: classical-planarian-nodejs
    janus-idp.io/tekton: classical-planarian-nodejs 
    backstage.io/kubernetes-id: classical-planarian-nodejs 
    backstage.io/techdocs-ref: dir:. 
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:classical-planarian-nodejs
